<a href="https://colab.research.google.com/github/parvez2204/parvez2204/blob/main/Neural_networks_prgm_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
scalar=tf.constant(7)
scalar
scalar.ndim

0

In [3]:
vector=tf.constant([10,10])

In [4]:
vector.ndim

1

In [5]:
matrix=tf.constant([[1,2],[3,4]])
print(matrix)
print( 'the number of dimensions of a matrix is :' +str(matrix.ndim))

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
the number of dimensions of a matrix is :2


In [6]:
matrix = tf.constant([[1,2],[3,4]])
matrix1 = tf.constant([[2,4],[6,8]])

In [7]:
print(matrix+matrix1)
print(matrix1-matrix)
print(matrix*matrix1)
print(matrix1/matrix)

tf.Tensor(
[[ 3  6]
 [ 9 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 2  8]
 [18 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2. 2.]
 [2. 2.]], shape=(2, 2), dtype=float64)


In [8]:
matrix=tf.constant([[1,2],[3,4]])
print(matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [9]:
print(tf.transpose(matrix))

tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


In [10]:
print('dot product of matrices is :' + str(tf.tensordot(matrix,matrix,axes=1)))

dot product of matrices is :tf.Tensor(
[[ 7 10]
 [15 22]], shape=(2, 2), dtype=int32)
